[package]
name = "i3-auto-layout"
version = "0.1.0"
authors = ["greg <gregory.mkv@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-i3ipc = { git = "https://github.com/leshow/tokio-i3ipc" }
futures-preview = "0.3.0-alpha.18"
tokio = "0.2.0-alpha.2"
anyhow = "1.0.16"
