[package]
name = "i3-auto-layout"
version = "0.1.0"
authors = ["greg <gregory.mkv@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-i3ipc = { git = "https://github.com/leshow/tokio-i3ipc" }
futures = { version = "0.3.1", default-features = false }
tokio = { version = "0.2.2", default-features = false, features = ["rt-threaded", "macros"] }
anyhow = "1.0.25"
